### ISSUE TITLE
Fail on compile: cython is needed for the installation

### ISSUE THREAD

**Issue by ybarlev** [sdsc/hdf-roll#1]
Should cython be installed in a separate roll? Couldn't find cython-roll.
# 

File "/root/src/hdf-roll/BUILD/sdsc-h5py_py2.7-2.4.0/h5py-2.4.0/setup_build.py", line 99, in run
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
make[5]: **\* [build] Error 1
make[5]: Leaving directory `/root/src/hdf-roll/BUILD/sdsc-h5py_py2.7-2.4.0'
make[4]: *** [build] Error 2
make[4]: Leaving directory`/root/src/hdf-roll/BUILD/sdsc-h5py_py2.7-2.4.0'
error: Bad exit status from /var/tmp/rpm-tmp.r8GaSf (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.r8GaSf (%build)
make[3]: **\* [rpm] Error 1
make[3]: Leaving directory `/root/src/hdf-roll/src/h5py'
make[2]: *** [rpm] Error 2
make[2]: Leaving directory`/root/src/hdf-roll/src'
make[1]: **\* [rpms] Error 2
make[1]: Leaving directory `/root/src/hdf-roll'
make: **\* [default] Error 2

**Comment by jjhayes** [comment]
cython is installed by the SDSC python-roll, along with several other python modules.  I'll add that to the roll doc.

**Comment by jjhayes** [comment]
I've updated the README.md of both the python-roll and the hdf-roll to indicate that the python-roll satisfies this dependency.
